name: Devops project 1
on: push
jobs:
  devpro1-ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set-up python
        uses: actions/setup-python@v4
        
        
      - name: Install dependencies 
        run: pip install -r requirements.txt
